POST http://localhost:8000/quizzo/post_quiz/
	content-type: application/json

	{
		"quizName" : "newQuiz",
		"data" : {
			"Q1" : "A1",
			"Q2" : "A2",
			"options" : {
				"Q1" : ["A", "A1", "C", "D"],
				"Q2" : ["A2", "B", "C", "D"]
			}
		}
	}
###



GET http://localhost:8000/quizzo/get_all_quiz